name: 'Sonarqube Scanner'
description: 'Scan code using Sonarqube'
author: 'MindDoc GmbH'
inputs:
  projectName:
    description: 'project name'
    required: true
  sources:
    description: 'analysis sources'
    required: true
  token:
    description: 'Sonar token string'
    required: true
  host:
    description: 'Sonar server host'
    required: true
  inclusions:
    description: 'Sonar code inclusions'
  exclusions:
    description: 'Sonar code exclusions'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'blue'
